# Stages definition
stages:
  - test
  - build

# Jobs
unit-test:
  image: golang:1.23-alpine
  before_script:
    - apk add --no-cache git
    - git config --global url.https://${MS_PACKAGE_USER}:${MS_PACKAGE_TOKEN}@${CI_SERVER_HOST}.insteadOf https://${CI_SERVER_HOST}
    - export GOPRIVATE=${CI_SERVER_HOST}
  stage: test
  script:
    - go test ./...

build-merge:
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  only:
    - main
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build --build-arg GO_MODULES_USER=${MS_PACKAGE_USER} --build-arg GO_MODULES_PERSONAL_ACCESS_TOKEN=${MS_PACKAGE_TOKEN} -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

build:
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  only:
    - tags
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - VERSION=$(echo "$CI_COMMIT_REF_NAME" | sed 's/^v//')
  script:
    - docker build --build-arg GO_MODULES_USER=${MS_PACKAGE_USER} --build-arg GO_MODULES_PERSONAL_ACCESS_TOKEN=${MS_PACKAGE_TOKEN} -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION